name = "hello-worker"
type = "webpack"
account_id = "ca1cf3142035cda538478428a5a42ff9"
workers_dev = true

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
zone_id = ""
route = "saidatr.dev/*"